#
# Basic settings.
#
url: http://hjop.kmz-brno.cz
title: hJOP – SW pro řízení modelové železnice
description: Some descriptions of yourself.
avatar: /assets/img/ogp.png
favicon: /assets/img/ogp.png
language: en

#
# Icons
#
icons:
  rss: true
  email:
  github: ttskch
  bitbucket:
  twitter: ttskch
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
