#
# Basic settings.
#
url: http://hjop.kmz-brno.cz
title: hJOP
description: Komplexní řešení řízení modelového kolejiště dle ZTP-JOP
avatar: /assets/img/hJOP.svg
favicon: /assets/img/hJOP.ico
language: cs
author: Jan Horáček
keywords: hJOP,JOP,vláček,model,sw,program
robots: index,follow

#
# Icons
#
icons:
  rss: false
  email: jan.horacek@kmz-brno.cz
  github: kmzbrnoI
  bitbucket:
  twitter:
  facebook: kmzbrnoI
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Gems.
#
plugins:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", ".htaccess"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - Makefile
